config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :index, :show, :edit, :create, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  patch 'books/:id' => 'books#update', as: 'update_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }
    
    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
    
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates_uniqueness_of :book_id, scope: :user_id
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller? 
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id
        comment.save
        redirect_to book_path(book)
    end
    
    def destroy
        BookComment.find(params[:id]).destroy
        redirect_to book_path(params[:book_id])
    end

    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end

    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :correct_user, only: [:edit, :update]
  
  def new
    @book = Book.new  
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id) 
    else
       render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to user_path
    end
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: root_path)
    end

    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

  before_action :ensure_correct_user, only:[:edit]
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = current_user.books
    @books = @user.books
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @users = User.all
    @user = current_user
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
      params.require(:user).permit(:name, :image, :introduction)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper


end
    

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %> error prohibited this obj from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
</div>


<h1>Editing Book</h1>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  
<% end %>

<a><%= link_to "Show", book_path(@book) %></a>
|
<a><%= link_to "Back", books_path %></a>

app/views/books/index.html.erb
<div class="container">
<div class="row">
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %> error prohibited this obj from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
</div>

<div class="col-md-3">
  <%= render 'users/list', book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <thead>
    <th>Title</th>
    <th>Opinion	</th>
    <th colspan="5"></th>
  </thead>
<tbody>
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to user_path(book.user.id) do %>
    <%= image_tag book.user.get_profile_image(80,80)  %>
    <% end %>
    </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
    <% if book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
			<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
			<%= book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :post do %>
			<i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
			<%= book.favorites.count %>
      <% end %>
    </td>
    <% end %>
    <td>コメント数:<%= book.book_comments.count %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
<div class="row">

<div class="col-md-3 offset-md-1">
<%= render 'users/list', book: @new_book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
    <tbody>
      <tr>
        <td>
          <%= image_tag @book.user.get_profile_image(100,100) %><br>
          <%= link_to @book.user.name, user_path(@book.user.id) %>
        </td>
        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>
        <% if @book.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
        <% end %>
        
        <% if @book.favorited_by?(current_user) %>
        <td>
          <%= link_to book_favorites_path(@book), method: :delete do %>
    			<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    			<%= @book.favorites.count %>
          <% end %>
        </td>
        <% else %>
        <td>
          <%= link_to book_favorites_path(@book), method: :post do %>
    			<i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
    			<%= @book.favorites.count %>
          <% end %>
        </td>
        <% end %>
        
        <td>コメント数:<%= @book.book_comments.count %></td>
        
      </tr>
    </tbody>
</table>

<div>
  <% @book.book_comments.each do |book_comment| %>
    <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
    <%= book_comment.user.name %>
    <%= book_comment.comment %>
  <% if book_comment.user == current_user %>
    <%= link_to 'Destroy', book_book_comment_path(@book, book_comment), method: :delete, class:'btn btn-danger' %>
  <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信" %>
  <% end %>
</div>


</div>
</div>
</div>

app/views/homes/about.html.erb
<h2>Welcome to <i class = 'fas fa-book'></i>Bookers!</h2>
<footer>
    <div>
        <p>CopyRight Inflatop.inc</p>
    </div>
</footer>

app/views/homes/top.html.erb
<div class="container">
<div class="row">

<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h2>Welcome to <i class="fas fa-book"></i>Bookers!</h2>
    
    <p>
      In <i class="fas fa-book"></i>Bookers, <br>
      you can share and exchange your opinions , <br>
      inpressions , and emotions about various books!
    </p>

    <div>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-sm btn-block" %>
    </div>
    <div>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info btn-sm btn-block mb-3" %>
    </div>
</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <%= link_to "Bookers", root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
        
        <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <%= link_to users_path, class: 'nav-link text-light' do %>
        <i class="fas fa-users"></i></i> Users
        <% end %>
      </li>
      <li>
        <%= link_to books_path, class: 'nav-link text-light' do %>
        <i class="fas fa-book-open"></i> Books
        <% end %>
        </a>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to root_path, class: 'nav-link text-light' do %>
        <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <%= link_to home_about_path, class: 'nav-link text-light' do %>
        <i class="fas fa-link"></i> About
        <% end %>
      </li>
      <li>
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
        <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i> Log in
        <% end %>
      </li>
    <% end %>
  </ul>
  </div>
  </nav>
  </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  
  <footer>
    <div class="container">
    <div class="row">
      <div class = "mx-auto"><p>CopyRight Infratop.inc</p></div>
  </footer>
    </div>
    </div>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody>
    <th>name</th>
    <td><%= user.name %></td>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</tbody>
</table>
<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
<%= form_with model: book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' , class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<div>
<% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved:<br>
    <% @user.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
</div>

<h2>User info</h2>
<%= form_with model: @user, method: :patch do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
</div>

<div class="container">
<div class="row">

<div class="col-md-3 offset-md-">
  <%= render 'list', book: @book, user: @user %>
</div>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </thead>
      <tbody>
          <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved:<br>
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>
</div>

<div class="container">
<div class="row">

<div class="col-md-3">
  <%= render 'list', book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <th>Title</th>
      <th>Opinion	</th>
    </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %></td>
      <% end %>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      
      <% if book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :delete do %>
			<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
			<%= book.favorites.count %>
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book.id), method: :post do %>
			<i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
			<%= book.favorites.count %>
      <% end %>
    </td>
    <% end %>
    <td>コメント数:<%= book.book_comments.count %></td>
      
      
    </tr>
    <% end %>
  </tbody>
  </table>
  </div>
</div>
</div>